"""add_role_permission_tables

Revision ID: 081a59424b88
Revises: 
Create Date: 2026-03-31 12:31:19.130003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081a59424b88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限编码'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='权限类型: api-接口, button-按钮, menu-菜单'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='API路径'),
    sa.Column('method', sa.String(length=20), nullable=True, comment='请求方法: GET/POST/PUT/DELETE'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级权限ID（菜单树）'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
